---
title: "Task6"
author: "Brady Monks"
date: "9/17/2020"
output: 
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plot Replication

I chose a plot that compared the GDP Per Capita to the Life Expectancy at birth. I was able to come up an extremely close parallel.  

```{r, echo=FALSE}

library(tidyverse)
library(ggrepel)
data1 <- read_csv("life-expectancy-vs-gdp-per-capita.csv")
data2015 <- filter(data1, Year == 2015)
data2015 <- data2015 %>%
  rename(
    GDP_Per_Capita_USD = "Real GDP per capita in 2011US$, multiple benchmarks (Maddison Project Database (2018))",
    Life_expectancy = "Life expectancy",
    Total_Population = "Total population (Gapminder, HYDE & UN)",
    Country = "Entity"
  )
data2015v2 <- na.omit(data2015)
ggplot(data = data2015v2)+
  geom_point(mapping = aes(x = GDP_Per_Capita_USD, y = Life_expectancy, size = Total_Population/10000, color = Continent))+
  geom_text_repel(aes(x = GDP_Per_Capita_USD, y = Life_expectancy, label = ifelse(Total_Population>75000000,as.character(Country),'')))+
  labs(x = "GDP per capita",
       y = "Life expectancy at birth",
       title = "Life expectancy vs. GDP per capita, 2015",
       subtitle = "GDP per capita is measured in 2011 international dollars, which corrects for inflation and cross-country price differences.")+  
  guides(size = FALSE)+
  scale_x_continuous(breaks = seq(0,120000, by = 20000),labels=scales::dollar_format())+
  scale_y_continuous(breaks = seq(50 , 80 , by = 5 ))+
  scale_color_manual(values = c("darkmagenta", "cyan4","slategray4","brown3","salmon3","maroon"))+
  theme(plot.title = element_text(hjust = 0),
        panel.background = element_rect(fill = "white"),
        panel.grid.major.x = element_line(colour = "grey",linetype = 2),
        panel.grid.major.y = element_line(colour = "grey",linetype = 2))


```

## Child Mortality

I was able to come up with simple graphs looking at just the United States. Then I was able to group_by the continents and look at each continent's child_mort over about 300 years.

```{r, echo=FALSE}
library(tidyverse)
library(devtools)
devtools::install_github("drsimonj/ourworldindata")
df <- ourworldindata::child_mortality

dfUSA <- filter(df, country == "United States", year >= 1933, year <= 2013)
dfUSA
ggplot(data = dfUSA)+
  geom_point(mapping = aes(x = year, y = child_mort, size = population))
ggplot(data = dfUSA)+
  geom_point(mapping = aes(x = year, y = survival_per_woman, size = population))
ggplot(data = dfUSA)+
  geom_point(mapping = aes(x = year, y = deaths_per_woman, size = population))+
  scale_x_continuous(breaks = seq(1930,2020, by = 15))

dfWorld <- group_by(df, continent, year)
dfworldsum <- summarise( dfWorld, 
                         child_mort = mean(child_mort, na.rm = TRUE))

ggplot(data = dfworldsum)+
  geom_line(mapping = aes(x = year, y = child_mort, color = continent))+
  facet_wrap(~continent)



```


