---
title: "Task9"
author: "Brady Monks"
date: "9/24/2020"
output: html_document
---

## Strengths

I believe I have a couple strengths. Some might see it as a weakness, but I think it's a strength that I'm willing to look at outside resources (other peole, online help) when I am stuck on some code. I don't usually like to be stubborn on code and be stuck for an hour. Another strength is that I can recognize whether a graph/plot is aesthetic and whether it can be tweaked to look better. Another strength is that I believe that I'm a people person and can be approached by anyone that needs help with anything work related or other. 

## Areas to Improve

Something I really struggle with is the fine tuning of the datasets. If I get some error or warning messages, I often have no idea how to go about those erros and correct them.I'm getting better at dissecting the errors and figuring out where to go from there. Another area to improve would be my graph-making. I don't quite know all the aesthetics yet. Like I said in my strengths, I can recognize what can be improved in a graph, I just can improve my actual ability to improve the graph. 

## Goals

By the end of this class, I hope to be able to look at a dataset and know how to clean it up so that it can be interpreted correctly by r and can be used fluently in making aesthetic visuals without any errors. 
